/* AETHEL Statistics: static page. The bot passes ?report=<Supabase public object URL>. */
const demo={master_name:'AETHEL',generated_at:new Date().toISOString(),total_stats:{total_appointments:42,completed:31,upcoming:7,canceled:4,total_income:62800,avg_check:2026},monthly_data:[['Апрель',42000],['Май',51000],['Июнь',62800]],service_stats:[{service:'Маникюр',count:14,income:29400},{service:'Окрашивание',count:9,income:20700},{service:'Ресницы',count:8,income:12700}],appointments:[],loyal_clients:[],sleeping_clients:[],lost_clients:[],new_clients:[],recommendations:['Напомните клиентам, которые не были больше 45 дней, о свободных окнах.','Услуга «Маникюр» даёт больше всего записей — закрепите для неё повторное предложение.']};
let report=demo, page=1; const perPage=12;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v)||0);
const date=v=>v?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)): '—';
const get=(...keys)=>{for(const k of keys){if(report[k]!==undefined&&report[k]!==null)return report[k]}return null};
function stats(){return Object.assign({total_appointments:0,completed:0,upcoming:0,canceled:0,total_income:0,avg_check:0},get('total_stats','totals')||{})}
function clients(){let a=[...(get('clients','client_stats')||[])]; if(!a.length){[['loyal_clients','loyal'],['new_clients','new'],['sleeping_clients','sleeping'],['lost_clients','lost']].forEach(([k,segment])=>(get(k)||[]).forEach(x=>a.push(Object.assign({},x,{segment}))));} return a.map(x=>({name:x.name||x.client_name||x.full_name||'Без имени',phone:x.phone||'—',username:x.username||x.telegram_username||'',segment:x.segment||'all',visits:x.visits||x.visit_count||x.total_visits||0,spent:x.spent||x.total_spent||0,last:x.last_visit||x.last_date,next:x.next_visit||x.next_date}));}
function appts(){return (get('appointments','all_appointments')||[]).map(x=>({date:x.datetime||x.work_date||x.date,client:x.client_name||x.name||'—',phone:x.phone||'',service:x.service||x.service_name||'—',master:x.master_name||report.master_name||'—',price:x.price||x.amount||0,status:x.status==='3'||x.status==='completed'?'completed':x.status==='2'||x.status==='cancelled'?'cancelled':x.status==='1'||x.status==='upcoming'?'upcoming':(new Date(x.datetime||x.work_date)>new Date()?'upcoming':'completed'),interval:x.interval_days||x.interval||null}));}
function setHtml(id,h){const e=$(id);if(e)e.innerHTML=h}
function kpi(label,value,delta=''){return `<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div>${delta?`<div class="kpi-delta">${delta}</div>`:''}</div>`}
function drawBars(el,data){if(!data?.length){setHtml(el,'<p class="muted">Недостаточно данных для графика.</p>');return}const max=Math.max(...data.map(x=>Number(x[1])||0),1);setHtml(el,data.map((x,i)=>`<div class="bar-row" style="display:grid;grid-template-columns:90px 1fr 90px;gap:10px;align-items:center;margin:17px 0"><small>${x[0]}</small><div class="bar"><i style="width:${(x[1]/max)*100}%"></i></div><small style="text-align:right">${money(x[1])}</small></div>`).join(''))}
function render(){const s=stats(), cs=clients(), as=appts(); $('#masterName').textContent=report.master_name||'Статистика мастера'; $('#updatedAt').textContent=report.generated_at?`обновлено ${date(report.generated_at)}`:'онлайн'; setHtml('#kpis',[kpi('Выполнено записей',s.completed||s.total_completed||0),kpi('Доход',money(s.total_income||s.income),s.total_income?'за весь период':''),kpi('Предстоящие',s.upcoming||0,'записи в календаре'),kpi('Отмены',s.canceled||s.cancelled||0)] .join('')); setHtml('#moneyKpis',[kpi('Средний чек',money(s.avg_check||((s.total_income||0)/(s.completed||1)))),kpi('Всего записей',s.total_appointments||as.length),kpi('Выполнено',s.completed||as.filter(x=>x.status==='completed').length),kpi('Доля отмен',`${Math.round(((s.canceled||0)/Math.max(1,s.total_appointments||1))*100)}%`)] .join('')); $('#avgCheck').textContent=money(s.avg_check||((s.total_income||0)/(s.completed||1))); const repeat=cs.filter(x=>x.visits>1).length/Math.max(1,cs.length); $('#repeatRate').textContent=Math.round(repeat*100)+'%'; drawBars('#incomeChart',get('monthly_data','monthly')||[]);drawBars('#incomeChartLarge',get('monthly_data','monthly')||[]);renderSegments(cs);renderServices();renderClients(cs);renderAppointments(as);renderForecast();renderInsights(s,cs);}
function renderSegments(cs){const counts={new:0,loyal:0,sleeping:0,lost:0};cs.forEach(x=>counts[x.segment]=(counts[x.segment]||0)+1);const labels={new:['Новые','первые визиты'],loyal:['Постоянные','возвращаются'],sleeping:['Спящие','давно не были'],lost:['Ушедшие','нужен возврат']};const h=Object.entries(labels).map(([k,v])=>`<div class="segment"><small>${v[0]}</small><b>${counts[k]||0}</b><small>${v[1]}</small></div>`).join('');setHtml('#clientSegments',h);setHtml('#clientSegmentsLarge',h)}
function renderInsights(s,cs){const rows=[];if(s.upcoming)rows.push(['Ближайшая загрузка',`В календаре ${s.upcoming} предстоящих записей.`]);if(cs.filter(x=>x.segment==='sleeping').length)rows.push(['Точка роста',`${cs.filter(x=>x.segment==='sleeping').length} клиентов давно не возвращались.`]);if(!rows.length)rows.push(['Хороший старт','Продолжайте собирать историю записей — рекомендации станут точнее.']);setHtml('#insights',rows.map(x=>`<div class="insight"><strong>${x[0]}</strong>${x[1]}</div>`).join(''));setHtml('#recommendations',(get('recommendations')||[]).map(x=>`<div class="insight">${x}</div>`).join('')||'<div class="insight">Рекомендации появятся после накопления данных.</div>')}
function renderServices(){const a=get('service_stats','services')||[];const max=Math.max(...a.map(x=>x.count||0),1);setHtml('#serviceMini',a.slice(0,4).map(x=>`<div class="service-row"><span>${x.service||x.name}</span><div class="bar"><i style="width:${(x.count/max)*100}%"></i></div><small>${x.count||0} записей</small></div>`).join('')||'<p class="muted">Нет данных об услугах.</p>');setHtml('#serviceBars',a.map(x=>`<div class="service-row"><span><b>${x.service||x.name}</b><br><small>${money(x.income||x.revenue)}</small></span><div class="bar"><i style="width:${(x.count/max)*100}%"></i></div><small>${x.count||0} записей</small></div>`).join('')||'<p class="muted">Нет данных об услугах.</p>');const sel=$('#serviceFilter');a.forEach(x=>{const o=document.createElement('option');o.value=x.service||x.name;o.textContent=o.value;sel.appendChild(o)})}
function renderClients(a){const q=($('#clientSearch')?.value||'').toLowerCase(), seg=$('#clientSegmentFilter')?.value||'all';a=a.filter(x=>(seg==='all'||x.segment===seg)&&`${x.name} ${x.phone} ${x.username}`.toLowerCase().includes(q));setHtml('#clientsTable',a.map(x=>`<tr><td><b>${x.name}</b><br><small class="muted">${x.username||x.phone}</small></td><td>${x.segment}</td><td>${x.visits}</td><td>${money(x.spent)}</td><td>${date(x.last)}</td><td>${date(x.next)}</td><td><button class="link-btn" onclick="alert('Средний интервал считается по истории визитов клиента')">Подробнее</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Ничего не найдено</td></tr>')}
function renderAppointments(a){const q=($('#appointmentSearch')?.value||'').toLowerCase(), st=$('#statusFilter')?.value||'all', sv=$('#serviceFilter')?.value||'all', from=$('#dateFrom')?.value, to=$('#dateTo')?.value; a=a.filter(x=>(st==='all'||x.status===st)&&(sv==='all'||x.service===sv)&&(!from||String(x.date)>=from)&&(!to||String(x.date)<=to)&&`${x.client} ${x.phone} ${x.service}`.toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(a.length/perPage));page=Math.min(page,pages);const slice=a.slice((page-1)*perPage,page*perPage);setHtml('#appointmentsTable',slice.map(x=>`<tr><td>${date(x.date)}<br><small class="muted">${x.date?.slice(11,16)||''}</small></td><td>${x.client}<br><small class="muted">${x.phone}</small></td><td>${x.service}</td><td>${x.master}</td><td>${money(x.price)}</td><td><span class="status ${x.status}">${x.status==='completed'?'Выполнена':x.status==='upcoming'?'Предстоит':'Отменена'}</span></td><td>${x.interval?x.interval+' дн.':'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Записей не найдено</td></tr>');$('#pageInfo').textContent=`${page} / ${pages}`}
function renderForecast(){const a=get('forecast','evolution_forecast')||[];setHtml('#forecastList',a.slice(0,8).map(x=>`<div class="forecast-row"><span>${x.month||x.period||'Период'}</span><b>${money(x.value||x.income||x.forecast)}</b></div>`).join('')||'<p class="muted">Прогноз появится после накопления нескольких периодов.</p>')}
async function load(){const url=new URLSearchParams(location.search).get('report');if(!url)return render();try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);report=await r.json();render()}catch(e){showToast('Не удалось загрузить отчёт. Проверьте ссылку.');render()}}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(x=>x.classList.toggle('active',x.id===b.dataset.section));scrollTo({top:0,behavior:'smooth'})});$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-section="${b.dataset.go}"]`).click());['clientSearch','clientSegmentFilter'].forEach(id=>$( '#'+id)?.addEventListener('input',()=>renderClients(clients())));['appointmentSearch','statusFilter','serviceFilter','dateFrom','dateTo'].forEach(id=>$( '#'+id)?.addEventListener('input',()=>renderAppointments(appts())));$('#incomePeriod')?.addEventListener('change',render);$('#prevPage').onclick=()=>{page=Math.max(1,page-1);renderAppointments(appts())};$('#nextPage').onclick=()=>{page++;renderAppointments(appts())};$('#printBtn').onclick=()=>print();load();
